#######################################################################################################################
### Copyright (c) 2022-2023 Advanced Micro Devices, Inc. All rights reserved.
### \author AMD Developer Tools Team
#######################################################################################################################

# Include the self capture apps
add_subdirectory(matrix_mul_dispatch_counter)
