// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

/// @author AMD Developer Tools Team
/// @file
/// @brief  Command line parser class definition

#ifndef RDP_SOURCE_SERVICE_CLI_COMMAND_LINE_PARSER_H_
#define RDP_SOURCE_SERVICE_CLI_COMMAND_LINE_PARSER_H_

#include "command_line_parameter.h"

#include <string>
#include <vector>

class CommandLineParser
{
public:
    /// @brief Constructor
    /// @param [in] argc The number of arguments on the commandline.
    /// @param [in] argv An array of argument strings on the command line.
    CommandLineParser(int argc, char** argv);

    /// @brief Adds a commandline parameter to be parsed.
    /// @param [in] parameter A pointer to a CommandLineParameter definition.
    void AddParameter(CommandLineParameter* parameter);

    /// @brief Defines the help option for the commandline.
    /// @param [in] name The string for the commandline option used to display a help message
    /// for all defined parameters.
    /// @param [in] description Help information for using the help option.
    void SetHelpOption(const char* name, const char* description);

    /// @brief Parses the defined parameters for a commandline.
    /// @return True if all specified parameters are valid, otherwise returns false.
    bool Parse();

    /// @brief Returns the error string generated by the Parse() method when invalid parameters
    /// are parsed on the commandline.
    /// @return The error string.
    [[nodiscard]] const std::string& ErrorString() const;

    /// @brief Builds and returns a help message string for all of the defined parameters
    /// @return The generated help string.
    [[nodiscard]] const std::string& HelpString() const;

    /// @brief Indicates that the help option (defined with SetHelpOption() method) is
    /// present on the commandline.
    /// @return True if the help option is present after parsing the commandline,
    /// otherwise returns false.
    [[nodiscard]] bool IsHelpRequested() const;

protected:
    /// @brief Searches all defined commandline parameters for one matching the parameter name
    /// @param [in] parameter_name A string containing the name of the parameter to match.
    /// @return A pointer to the CommandlineParameter definition that matches the string with
    /// the name matching the parameter_name argument.  Null is returned if a match is not found.
    [[nodiscard]] CommandLineParameter* MatchParameter(const std::string& parameter_name) const;

private:
    /// @brief Processes a single command line argument.
    /// @param [in,out] iter Iterator to the current argument (may be advanced for value parameters).
    /// @param [out] error Output error string.
    /// @return True if the argument was processed successfully.
    bool ProcessSingleArgument(std::vector<std::string>::iterator& iter, std::string& error);

    std::vector<CommandLineParameter*> defined_parameters_;       ///< List of commandline parameter definitions.
    std::vector<std::string>           command_line_arguments_;   ///< List of items specified on the commandline.
    std::string                        error_string_;             ///< Error string generated after parsing the commandline.
    std::string                        help_option_name_;         ///< Commandline option used to display a help message.
    std::string                        help_option_description_;  ///< Description of the help option.
    bool                               help_option_found_;        ///< Indicates that the help option was specified on the commandline.
};
#endif
