#######################################################################################################################
### Copyright (c) 2023 Advanced Micro Devices, Inc. All rights reserved.
### @author AMD Developer Tools Team
#######################################################################################################################

add_executable(DeployQtHelper deploy_qt_helper.cpp)
devtools_target_options(DeployQtHelper)
